### ISSUE TITLE
Unable to execute HTTP request: sts.amazonaws.com

### ISSUE THREAD

**Issue by dbbaskette** [sequenceiq/cloudbreak-deployer#147]
I have installed CB as instructed, but when I try to create my AWS credential I get an error:
cloudbreak_1 | 2015-11-03 15:22:47,537 [http-nio-8080-exec-3] badRequest:42 ERROR c.s.c.c.ExceptionControllerAdvice – [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Failed to import public key [roleArn:’arn:aws:iam::337….445:role/cb-access’], detailed message: Unable to execute HTTP request: sts.amazonaws.com
cloudbreak_1 | com.sequenceiq.cloudbreak.controller.BadRequestException: Failed to import public key [roleArn:’arn:aws:iam::337….445:role/cb-access’], detailed message: Unable to execute HTTP request: sts.amazonaws.com

I had this a couple weeks ago, but I managed to get past it, but my VM I was using for the Docker images got corrupted, and now I can’t seem to get past this issue this time around.

**Comment by lalyos** [comment]
hi @dbbaskette, looks like the container running cloudbreak-api (creak_cloudbreak_1 container) has no internet connection, or uses a bad dans server. To check which happens:

## check network connection
```
docker exec cbreak_cloudbreak_1 ping 8.8.8.8
```

## check dans server
```
docker exec cbreak_cloudbreak_1 ping google.com
```

If Both succeed, than you can check these to command for all other containers..

I suspect, that you do have network connection, but dns fails. If you use `cbd` on OSX, mostly it happens when you change network while **boot2docker** is running. In that case please restart it:
```
boot2docker restart
```

**Comment by dbbaskette** [comment]
That helped.  I am on centos, and ANY change to networking including stopping the firewall caused issue.   Once I turned off the firewall with chkconfig and restarted....  i was able to save the cred.  Thanks and this explains why I got past it once (Luck)
