### ISSUE TITLE
cbd can't recognise proxy

### ISSUE THREAD

**Issue by ylvmw** [sequenceiq/cloudbreak-deployer#170]
Hello,

Is there a way to set the http proxy for cbd? I need to access the internet via proxy.

Thanks!

**Comment by ylvmw** [comment]
Found it: 
just add the env variables to the Profile:
export http_proxy=your_proxy_url
export https_proxy=your_proxy_url

**Comment by lalyos** [comment]
thanks for the reference

**Comment by jessehu** [comment]
We're still struggling on the proxy issue. 'cbd init' hung for several minutes and exit with 52.  Setting 'export http_proxy=http://proxy.mydomain.com:3128; export https_proxy=http://proxy.mydomain.com:3128' in the bash doesn't help.  We can confirm it's due to 'cbd' doesn't read the https_proxy env variable.

localhost:cbd-local $ cbd init
* Dependency required, installing aws latest ...
localhost:cbd-local $ echo $?
52

**Comment by lalyos** [comment]
cbd init first starts by downloading binary dependencies such as sed,jq ... It downloads it with curl, but curl should use the `http_proxy` en variable...

You can rerun init in debug mode (actually any cbd command) by:
```
DEBUG=1 cbd init
```
to see which exact command hangs

**Comment by jessehu** [comment]
Thanks @lalyos but no debug info printed:
```
DEBUG=1 cbd init
* Dependency required, installing sed latest ...

DEBUG=10 cbd init
* Dependency required, installing sed latest ...
```

**Comment by lalyos** [comment]
ok lets go for even more detail with:
```
TRACE=1 cbd init
```

**Comment by jessehu** [comment]
Here is the output:
```
$ echo $http_proxy 
http://proxy.mydomain.com:3128
$ echo $https_proxy 
http://proxy.mydomain.com:3128
$ TRACE=1 cbd init
... ...
+ tmpfile=/Users/serengeti/code/sequenceiq/CloudBreakDeployer/.deps/tmp/download/sed
+ curl -Ls https://github.com/sequenceiq/gnused-osx-bin/releases/download/v4.2.2/sed-darwin-4.2.2.tgz
```

**Comment by lalyos** [comment]
I see, @jessehu you have to add the http env vars into your Profile
```
cat >> Profile <<EOF
export http_proxy=http://proxy.mydomain.com:3128
export https_proxy=http://proxy.mydomain.com:3128
EOF
```

cbd starts a new bash proces which doesn't inherits the env vars from the shell you are.

**Comment by jessehu** [comment]
I got the same result after adding proxy in Profile.
```
$ head Profile 
export http_proxy=http://proxy.vmware.com:3128
export https_proxy=http://proxy.vmware.com:3128
```
```
$ TRACE=1 cbd init
... ...
+ mkdir -p /Users/serengeti/code/sequenceiq/CloudBreakDeployer/.deps/bin
++ curl -s https://raw.githubusercontent.com/lalyos/glidergun-rack/master/index/sed
+ index='# install: mv sed $PREFIX/bin

latest linux_amd64 https://github.com/sequenceiq/docker-gnused-linux-bin/releases/download/v4.2.2/sed-linux-4.2.2.tgz a9404833974aea2356e2c984d30fed9e
latest darwin_amd64 https://github.com/sequenceiq/gnused-osx-bin/releases/download/v4.2.2/sed-darwin-4.2.2.tgz f0fb77edffd31acfa0e2916ba87f7f1a

4.2.2 linux_amd64 https://github.com/sequenceiq/docker-gnused-linux-bin/releases/download/v4.2.2/sed-linux-4.2.2.tgz a9404833974aea2356e2c984d30fed9e
4.2.2 darwin_amd64 https://github.com/sequenceiq/gnused-osx-bin/releases/download/v4.2.2/sed-darwin-4.2.2.tgz f0fb77edffd31acfa0e2916ba87f7f1a'
......
+ mkdir -p /Users/serengeti/code/sequenceiq/CloudBreakDeployer/.deps/tmp/download
+ tmpfile=/Users/serengeti/code/sequenceiq/CloudBreakDeployer/.deps/tmp/download/sed
+ curl -Ls https://github.com/sequenceiq/gnused-osx-bin/releases/download/v4.2.2/sed-darwin-4.2.2.tgz
(hung for minutes then exit with 57)
```

**Comment by lalyos** [comment]
Maybe your proxy server doesn't allow it?

Can this single line download and unzip a `sed` binary:
```
curl -L https://github.com/sequenceiq/gnused-osx-bin/releases/download/v4.2.2/sed-darwin-4.2.2.tgz | tar xzv
```

**Comment by jessehu** [comment]
Yes, I can use curl directly to download it with https_proxy set.

**Comment by ylvmw** [comment]
Set the proxy env variables to the Profile does not solve the problem. Sorry for the mistake.

**Comment by lalyos** [comment]
Ok i found the issue: the curl happens before `Profile` is loaded. I'll create a fix for the 1.1.0 branch and when it works, merge to master. Which version are you using guys?

**Comment by jessehu** [comment]
I'm using 1.0.3.  Can cbd read https_proxy env variables too ? Then no need to set it in Profile.

**Comment by lalyos** [comment]
ok i will merge the fix for the 1.0.3 branch as well.

> Can cbd read https_proxy env variables too ?
No, thats the thing cbd deliberatly opens a new bash process without inheriting any env vars. The only way to set env vars to cbd is to put the into `Profile`. 

But loading the profile has to happen earlier, so that the first curl can take http_xxx env settings into account. I'll provide a fixed version soon.

**Comment by lalyos** [comment]
@jessehu could you please try this version, it its fixing the proxy issue:

## linux
```
curl -s https://circle-artifacts.com/gh/sequenceiq/cloudbreak-deployer/1203/artifacts/0/tmp/circle-artifacts.OOWYDET/cbd-linux.tgz | tar -xzv -C /usr/local/bin
```

## osx
```
curl -s https://circle-artifacts.com/gh/sequenceiq/cloudbreak-deployer/1203/artifacts/0/tmp/circle-artifacts.OOWYDET/cbd-darwin.tgz | tar -xzv -C /usr/local/bin
```

## check
You should have than the following version:
```
cbd --version
CloudBreak Deployer: 1.0.4-fix-proxy-f178dc3
```

**Comment by lalyos** [comment]
btw, i would strongly recommend to use 1.1.0-rc as it has a tons of fixes. Its documentation can be found here: http://sequenceiq.com/cloudbreak-docs/release-1.1.0/

You can install it as:
```
curl -Ls public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_1.1.0-rc3_$(uname)_x86_64.tgz | sudo tar -xz -C /usr/local/bin cbd
```

**Comment by jessehu** [comment]
The https_proxy in Profile works. Thanks a lot for the quick fix @lalyos . I will use 1.1.0 instead.

**Comment by lalyos** [comment]
ok, i will cherry pick the same fix for master and 1.1.0 branches, today, and provide instructions here.

**Comment by lalyos** [comment]
the fix is merged to the master and 1.1.x branch, so you can update to it as:
```
cbd update fix-proxy
```
## check
You should have than the following version:
```
cbd --version
Cloudbreak Deployer: 1.1.0-fix-proxy-9f617c2
```

**Comment by jessehu** [comment]
To summarize, the following setting is needed in Profile when using http_proxy:

···
export http_proxy=http://proxy.vmware.com:3128
export https_proxy=http://proxy.vmware.com:3128
export no_proxy=192.168.59.103
···
the no_proxy line is needed, otherwise ’cbd init' will complain TLS error.

BTW,  I tried to run "export TRACE=1; cbd init" and found cbd will run in TRACE mode, which means cbd can read the TRACE env variable. So I guess cbd should be able to read the http_proxy vars in 'load-profile‘ function.

**Comment by lalyos** [comment]
> BTW, I tried to run "export TRACE=1; cbd init" and found cbd will run in TRACE mode, which means cbd can read the TRACE env variable. So I guess cbd should be able to read the http_proxy vars in 'load-profile‘ function.

> So I guess cbd should be able to read the http_proxy
No thats not true. As I said previously cbd runs in a new process which doesnt inherits env vars. Except a few, like `DEBUG`, `TRACE`, `HOME`, but nothing else: https://github.com/sequenceiq/cloudbreak-deployer/blob/master/deployer.go#L55-L58

But this is again what we want: not to inherit env vars (other than DEBUG/TRACE/HOME) from parent process, only the declarative list in `Profile`

**Comment by jessehu** [comment]
thanks for the explaintion. that's what i mean, exporting HTTPS_PROXY,HTTP_PROXY,NO_PROXY as well.  It's no halm but convenient because users don't need to add the proxy setting in Profile again, just like curl,wget,yum read the proxy setting from OS.

Jesse
sent from my mobile

在 lalyos <notifications@github.com>，2016年1月6日 下午10:50写道：

BTW, I tried to run "export TRACE=1; cbd init" and found cbd will run in TRACE mode, which means cbd can read the TRACE env variable. So I guess cbd should be able to read the http_proxy vars in 'load-profile‘ function.

So I guess cbd should be able to read the http_proxy
No thats not true. As I said previously cbd runs in a new process which doesnt inherits env vars. Except a few, like DEBUG, TRACE, HOME, but nothing else: https://github.com/sequenceiq/cloudbreak-deployer/blob/master/deployer.go#L55-L58<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sequenceiq_cloudbreak-2Ddeployer_blob_master_deployer.go-23L55-2DL58&d=BQMFaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=B9MrrzU1mdfLkLc-LCmMDw&m=JHY_Pfwg_enw6TCdC2G1TJ75dgdsEXZ3tYOedj3gnUk&s=1Sf_Ne19vXx6m-7ESIpd4xtWef2A91Ljv5r0PgPlbX4&e=>

But this is again what we want: not to inherit env vars (other than DEBUG/TRACE/HOME) from parent process, only the declarative list in Profile

**Comment by lalyos** [comment]
I see. Well it make sense to inherint proxy env vars ... The only thing is in that case we would say: cbd doesn't inherit env vars except: and list with 6-7 ... items. Let me think about

**Comment by chhetrid** [comment]
Hello,

We are running into this proxy issues as well ... 

Running version 1.1.0 on AWS - strictly following the documentation at hortonworks/sequenceiq and using the recommended image.

http_proxy and https_proxy variables are set in appropriate place (including Profile) and internet access through proxy work fine for tools like python pip, curl, yum etc., but for cbd.

Please note that I have read through this thread and tried everything/anything :-) but have not been able to complete the manage credentials step - so it is preventing us from doing much. 

Any recommendations/suggestions/tips will be much appreciated.

thanks,

Dilip

**Comment by chhetrid** [comment]
Correction:
Well certain portion of the cbd seem to be working fine - e.g. updating from 1.1.0-rc3-3df1cc2 to 1.1.0 worked fine - just puzzling.

**Comment by lalyos** [comment]
Hi @chhetrid, we have localised the root of the issue:

Apache HttpClient, which is used by a couple of libraries we rely on, by default:
> will not make use of any Java system properties, nor of system or browser proxy settings

https://github.com/apache/httpclient/blob/4.5.x/httpclient/src/main/java/org/apache/http/impl/conn/DefaultRoutePlanner.java#L47-L48

These are the directions we are thinking about:
- Try to provide patch/pull-requests for the projects which are using Apache HttpClient. Make them configurable to use SystemDefaultRoutePlanner. This direction is the cleanest, but probably takes a lot of time, until each project acceppts the change, and releses a new version
- Patch the Apache HttpClient library itself, and use the patched version. This could be done quicker, but than any further dependency resolution should be checked at each release (in case some of the libraries start to refer to a never HttpClient version)
- Use some AOP technik to force proxy settings. Unfortunately in a couple of place the Constructor call needs to be @Around-ed. Spring AOP by default doesn't supports constructors, however if Aspectj and/or LoadTimeWeaving is used, its achivable.

We will check which one is the best solution and use that one.

**Comment by chhetrid** [comment]
Thanks @lalyos for your response. I am selfishly hoping this issue is on a "priority" list of items for resolution :-)
