### ISSUE TITLE
Pulling Containers in AWS

### ISSUE THREAD

**Issue by dischord01** [sequenceiq/cloudbreak-deployer#31]
I am trying to install cloudbreak in AWS on a AWS Linux instance with docker 1.5.0 installed, rebooted and started docker damon. I am running into a problem pulling containers. 

I cloned the cloudbreak-deployer repo and ran the one-liner to install cbd. 

I have created a "Profile" with the following info
```
export PUBLIC_IP=52.5.194.91
export CLOUDBREAK_SMTP_SENDER_USERNAME=cloudbreak
export CLOUDBREAK_SMTP_SENDER_PASSWORD=password123
export CLOUDBREAK_SMTP_SENDER_HOST=52.5.194.91
export CLOUDBREAK_SMTP_SENDER_PORT=993
export CLOUDBREAK_SMTP_SENDER_FROM=cloudbreak-mail
export DOCKER_HOST=52.5.194.91
export DOCKER_CERT_PATH="~/.ssh/id_rsa"
export DOCKER_TLS_VERIFY=false
```

I try to pull the container and I get this error
```
[root@ip-10-0-0-91 cloudbreak-deployer]# cbd pull
Can't find a suitable configuration file. Are you in the right directory?

Supported filenames: docker-compose.yml, docker-compose.yaml, fig.yml, fig.yaml
```

**Comment by lalyos** [comment]
Thanks for reporting, I just release a new version cbd: 0.1.0, Please update cbd with the command: 
```
cbd update
```
and check if you have the latest
```
cbd --version
CloudBreak Deployer: 0.1.0
```

# Since version 0.1.0
We reduced the required env variables to 1: **PUBLIC_IP**:
- DOCKER_XXX variables are inherited from the shell you run `cbd`
- we use an updated set of Docker images, with fix email configuration (Cloudbreak/Periscope/Uluwatu starts now fine without any smtp configuration, and writes mails to log by default)

# Failing `cbd pull`

You have to generate `docker-compose.yml` to be able to `pull`. The command is:
```
cbd generate
```

btw `cbd pull` should do the docker-compose.yml genertion if missing. Im going to fix that, Until that,
you can just run the `cbd generate` yourself.

**Comment by lalyos** [comment]
Unti l create a new release of cbd, you are still able to test the fix, by using the *snapshot*
Official releases are built from the **release** branche, but master is always built.

# Using snapshot build of cbd

```
cbd update master
cbd --version
CloudBreak Deployer: 0.1.0-master-9d7b140
```
With this version, even if you delete the *.yml files, you can issue `cbd pull`, it will create them, and pull the images.

**Comment by dischord01** [comment]
Thanks for the quick response!

**Comment by lalyos** [comment]
Developer experience is the new king ;)
