### ISSUE TITLE
Ubuntu issue. client vs. server mismatch

### ISSUE THREAD

**Issue by ckonstanski** [sequenceiq/cloudbreak-deployer#36]
I am trying to run cloudbreak on an Ubuntu 14.10 host. There's an issue that I'm only seeing on Ubuntu. (I do not see it on Gentoo and CentOS 7.)

root@ubuntu:~/cloudbreak-deployment# cbd pull
Pulling ambassador (progrium/ambassadord:latest)...
client and server don't have same version (client : 1.15, server: 1.14)

It doesn't matter if I use master or not. "cbd update" and "cbd update master" give the same results.

**Comment by ckonstanski** [comment]
What is your recommended distro? I'm having more subtle problems in CentOS 7 too. I'll try to avoid entering an issue if it works on your recommended OS. (Gentoo works great, but I'll never get anyone to agree to that.)

**Comment by lalyos** [comment]
First, you can always get more info in debug mode:
```
DEBUG=1 cbd whatever
```

> client and server don't have same version (client : 1.15, server: 1.14)

For `pull` pull is usin `docker-compose`, which in turn uses the docker client. So it looks like
the real problem is that docker client and server doesn't hve the same version.

But that is odd when you are logged on an ubuntu (or any linux) box and the docker client talks to the docker daemon on the same host, cient and server should be the same binary ...

Cold you please check what `docker version` reports?

**Comment by ckonstanski** [comment]
root@ubuntu:~/cloudbreak-deployment# docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.2.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.2.1
Git commit (server): fa7b24f

**Comment by ckonstanski** [comment]
root@ubuntu:~/cloudbreak-deployment# DEBUG=1 cbd pull
[DEBUG] Use profile: Profile
[DEBUG] CloudBreak Deployer 0.1.0-master-09a86e9
Pulling ambassador (progrium/ambassadord:latest)...
client and server don't have same version (client : 1.15, server: 1.14)

**Comment by ckonstanski** [comment]
I got the testing version of docker. It seems to be working now. Server API version = 1.18. This issue can be closed.
