### ISSUE TITLE
Default user in cloudbreak UI not disabled

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak-deployer#65]
Hi,

I recently installed DIY version of cloudbreak in AWS and I wanted to remove the default username/password (admin@example.com/cloudbreak). Hence I changed my Profile file to include the following:

export UAA_DEFAULT_USER_PW=cb1234
export UAA_DEFAULT_USER_EMAIL=cloudbreak@xyz.com

Now I can login with cloudbreak@xyz.com/cb1234 and also with the default credentials admin@example.com/cloudbreak. Is this because something am missing? Or is it a bug in cloudbreak deployer?

Thanks,
Malathi

**Comment by lalyos** [comment]
It is because you first started cloudbreak with default usep/pwd in au.yml. 
- When uaa (identity server) starts it stores everything in the au_db (postgres)
- At every change uaa does the same.

UAA isn't developed by us. But i guess it doesn't delete from the db, just adds new records.
So if you want to get rid of old data, just delete the dbs:

```
cbd delete
```
